// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks
#include "02_bionx_motor.h"
#include "mongoose_glue.h"
// motor.h
extern int16_t assistLevel;
extern uint16_t motorSpeed;
extern uint16_t motorPower;
extern uint16_t motorTemperature;
extern uint16_t motorStatus;
extern uint32_t motorVoltage;
extern int32_t gauge;
extern int16_t rekupLevel;
extern int32_t level;
extern int16_t motorlevel; 
int16_t webassistLevel;

static struct leds s_leds = {false};
void glue_get_leds(struct leds *data) {
  *data = s_leds;  // Sync with your device
}
void glue_set_leds(struct leds *data) {
  s_leds = *data; // Sync with your device
}




void glue_get_motor(struct motor *data) {
  data->power = motorPower;  // Sync with your device
  data->level = assistLevel;
  data->speed = motorSpeed;
}
void glue_set_motor(struct motor *data) {
  webassistLevel = data->level; // Sync with your device
}

static struct settings s_settings = {42, 42};
void glue_get_settings(struct settings *data) {
  *data = s_settings;  // Sync with your device
}
void glue_set_settings(struct settings *data) {
  s_settings = *data; // Sync with your device
}
